version: '3'
services:
  authserver:
    build:
      context: ./backends/authserver
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    depends_on:
      - mongodb
      - redis
    environment:
      - DB_CONNECT=mongodb://mongodb:27017/storems_auth
      - TOKEN_SECRET=NJD3402
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PORT=4001
    volumes:
      - ./backends/authserver:/app
    networks:
      - mynetwork
  productserver:
    build:
      context: ./backends/productserver
      dockerfile: Dockerfile
    ports:
      - '4002:4002'
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
      - DB_CONNECT=mongodb://mongodb:27017/storems_product
      - PORT=4002
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - AMQP_BASE=amqp://rabbitmq
    volumes: 
      - ./backends/productserver:/app
    networks:
      - mynetwork
  # userclient:
  #   build:
  #     context: ./frontends/users
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - productserver
  #     - authserver
  #   environment:
  #     - VUE_APP_PRODUCTION_MODE=true
  #     - VUE_APP_PRODUCTION_HOST=http://localhost
  #   volumes:
  #     - ./frontends/users:/app
  #   networks:
  #     - mynetwork
  authclient:
    build:
      context: ./frontends/authentication
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      - authserver
    environment:
      - VUE_APP_PRODUCTION_MODE=true
      - VUE_APP_PRODUCTION_HOST=http://localhost
    volumes:
      - ./frontends/authentication:/app
    networks:
      - mynetwork
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
  mongodb:
    image: mongo
    container_name: mongodb
    # restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    networks:
      - mynetwork
  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - authserver
      - productserver
      - mongodb
      - redis
      - rabbitmq
    networks:
      - mynetwork
networks:
  mynetwork: